# Generated by Django 5.2.5 on 2025-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название товара.', max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Артикул/код (необязательно).', max_length=64)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена.', max_digits=12, null=True)),
                ('currency', models.CharField(default='RUB', help_text='Валюта цены.', max_length=8)),
                ('photo', models.ImageField(blank=True, help_text='Локальный файл фото', null=True, upload_to='products/photos/')),
                ('bitrix_id', models.IntegerField(blank=True, db_index=True, help_text='ID товара в Битрикс24 (необязательно).', null=True)),
                ('description', models.TextField(blank=True, help_text='Описание/характеристики.')),
                ('is_active', models.BooleanField(default=True, help_text='Быстро выключить товар.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда создано.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Когда обновлялось.')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
