# Generated by Django 5.2.5 on 2025-08-15 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_qr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='products/qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_links', to='products_qr.product')),
            ],
            options={
                'verbose_name': 'Секретная ссылка на товар',
                'verbose_name_plural': 'Секретные ссылки на товар',
                'ordering': ['-created_at'],
            },
        ),
    ]
